[sender]
email : #add sender email here
password : #add APP pass here
host : smtp.gmail.com
port : 465

[reciever]
email_list : #add reciever email/s here

[time]
recording_ending_time : 1800
recording_time_delay : none
alert_start_time : none
alert_stop_time : none

[rtsp]
link : #add rtsp link here