# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Inference.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='Inference.proto',
  package='detections',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0fInference.proto\x12\ndetections\"\xc7\x01\n\x0f\x44\x65tectorResults\x12\x11\n\ttimestamp\x18\x01 \x01(\x04\x12\x0b\n\x03\x63\x61m\x18\x02 \x01(\t\x12\x13\n\x0bimage_width\x18\x03 \x01(\x05\x12\x14\n\x0cimage_height\x18\x04 \x01(\x05\x12 \n\x06\x62ounds\x18\x05 \x03(\x0b\x32\x10.detections.BBox\x12 \n\x05\x66rame\x18\x06 \x01(\x0b\x32\x11.detections.cvMat\x12%\n\x05\x63ount\x18\x07 \x01(\x0b\x32\x16.detections.FrameCount\"/\n\nFrameCount\x12\x0f\n\x07inCount\x18\x01 \x01(\x05\x12\x10\n\x08outCount\x18\x02 \x01(\x05\"\xb8\x01\n\x04\x42\x42ox\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\x12\r\n\x05width\x18\x03 \x01(\x02\x12\x0e\n\x06height\x18\x04 \x01(\x02\x12\r\n\x05score\x18\x05 \x01(\x02\x12\r\n\x05label\x18\x06 \x01(\t\x12\x0f\n\x07\x63lassid\x18\x07 \x01(\x05\x12\x11\n\tclassname\x18\x08 \x01(\t\x12\x0f\n\x07trackid\x18\t \x01(\x02\x12(\n\tlandmarks\x18\n \x01(\x0b\x32\x15.detections.Landmarks\"\xbd\x01\n\tLandmarks\x12\x10\n\x08lefteyeX\x18\x01 \x01(\x02\x12\x10\n\x08lefteyeY\x18\x02 \x01(\x02\x12\x11\n\trighteyeX\x18\x03 \x01(\x02\x12\x11\n\trighteyeY\x18\x04 \x01(\x02\x12\r\n\x05noseX\x18\x05 \x01(\x02\x12\r\n\x05noseY\x18\x06 \x01(\x02\x12\x10\n\x08lipleftX\x18\x07 \x01(\x02\x12\x10\n\x08lipleftY\x18\x08 \x01(\x02\x12\x11\n\tliprightX\x18\t \x01(\x02\x12\x11\n\tliprightY\x18\n \x01(\x02\"Y\n\x05\x63vMat\x12\x0c\n\x04rows\x18\x01 \x01(\x05\x12\x0c\n\x04\x63ols\x18\x02 \x01(\x05\x12\x10\n\x08\x65lt_type\x18\x03 \x01(\x05\x12\x10\n\x08\x65lt_size\x18\x04 \x01(\x05\x12\x10\n\x08mat_data\x18\x05 \x01(\x0c\x62\x06proto3')
)




_DETECTORRESULTS = _descriptor.Descriptor(
  name='DetectorResults',
  full_name='detections.DetectorResults',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='detections.DetectorResults.timestamp', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cam', full_name='detections.DetectorResults.cam', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='image_width', full_name='detections.DetectorResults.image_width', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='image_height', full_name='detections.DetectorResults.image_height', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='bounds', full_name='detections.DetectorResults.bounds', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='frame', full_name='detections.DetectorResults.frame', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='count', full_name='detections.DetectorResults.count', index=6,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=32,
  serialized_end=231,
)


_FRAMECOUNT = _descriptor.Descriptor(
  name='FrameCount',
  full_name='detections.FrameCount',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='inCount', full_name='detections.FrameCount.inCount', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='outCount', full_name='detections.FrameCount.outCount', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=233,
  serialized_end=280,
)


_BBOX = _descriptor.Descriptor(
  name='BBox',
  full_name='detections.BBox',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='detections.BBox.x', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='detections.BBox.y', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='width', full_name='detections.BBox.width', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='height', full_name='detections.BBox.height', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='score', full_name='detections.BBox.score', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='label', full_name='detections.BBox.label', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='classid', full_name='detections.BBox.classid', index=6,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='classname', full_name='detections.BBox.classname', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='trackid', full_name='detections.BBox.trackid', index=8,
      number=9, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='landmarks', full_name='detections.BBox.landmarks', index=9,
      number=10, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=283,
  serialized_end=467,
)


_LANDMARKS = _descriptor.Descriptor(
  name='Landmarks',
  full_name='detections.Landmarks',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='lefteyeX', full_name='detections.Landmarks.lefteyeX', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='lefteyeY', full_name='detections.Landmarks.lefteyeY', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='righteyeX', full_name='detections.Landmarks.righteyeX', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='righteyeY', full_name='detections.Landmarks.righteyeY', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='noseX', full_name='detections.Landmarks.noseX', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='noseY', full_name='detections.Landmarks.noseY', index=5,
      number=6, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='lipleftX', full_name='detections.Landmarks.lipleftX', index=6,
      number=7, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='lipleftY', full_name='detections.Landmarks.lipleftY', index=7,
      number=8, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='liprightX', full_name='detections.Landmarks.liprightX', index=8,
      number=9, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='liprightY', full_name='detections.Landmarks.liprightY', index=9,
      number=10, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=470,
  serialized_end=659,
)


_CVMAT = _descriptor.Descriptor(
  name='cvMat',
  full_name='detections.cvMat',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='rows', full_name='detections.cvMat.rows', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cols', full_name='detections.cvMat.cols', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='elt_type', full_name='detections.cvMat.elt_type', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='elt_size', full_name='detections.cvMat.elt_size', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mat_data', full_name='detections.cvMat.mat_data', index=4,
      number=5, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=661,
  serialized_end=750,
)

_DETECTORRESULTS.fields_by_name['bounds'].message_type = _BBOX
_DETECTORRESULTS.fields_by_name['frame'].message_type = _CVMAT
_DETECTORRESULTS.fields_by_name['count'].message_type = _FRAMECOUNT
_BBOX.fields_by_name['landmarks'].message_type = _LANDMARKS
DESCRIPTOR.message_types_by_name['DetectorResults'] = _DETECTORRESULTS
DESCRIPTOR.message_types_by_name['FrameCount'] = _FRAMECOUNT
DESCRIPTOR.message_types_by_name['BBox'] = _BBOX
DESCRIPTOR.message_types_by_name['Landmarks'] = _LANDMARKS
DESCRIPTOR.message_types_by_name['cvMat'] = _CVMAT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DetectorResults = _reflection.GeneratedProtocolMessageType('DetectorResults', (_message.Message,), dict(
  DESCRIPTOR = _DETECTORRESULTS,
  __module__ = 'Inference_pb2'
  # @@protoc_insertion_point(class_scope:detections.DetectorResults)
  ))
_sym_db.RegisterMessage(DetectorResults)

FrameCount = _reflection.GeneratedProtocolMessageType('FrameCount', (_message.Message,), dict(
  DESCRIPTOR = _FRAMECOUNT,
  __module__ = 'Inference_pb2'
  # @@protoc_insertion_point(class_scope:detections.FrameCount)
  ))
_sym_db.RegisterMessage(FrameCount)

BBox = _reflection.GeneratedProtocolMessageType('BBox', (_message.Message,), dict(
  DESCRIPTOR = _BBOX,
  __module__ = 'Inference_pb2'
  # @@protoc_insertion_point(class_scope:detections.BBox)
  ))
_sym_db.RegisterMessage(BBox)

Landmarks = _reflection.GeneratedProtocolMessageType('Landmarks', (_message.Message,), dict(
  DESCRIPTOR = _LANDMARKS,
  __module__ = 'Inference_pb2'
  # @@protoc_insertion_point(class_scope:detections.Landmarks)
  ))
_sym_db.RegisterMessage(Landmarks)

cvMat = _reflection.GeneratedProtocolMessageType('cvMat', (_message.Message,), dict(
  DESCRIPTOR = _CVMAT,
  __module__ = 'Inference_pb2'
  # @@protoc_insertion_point(class_scope:detections.cvMat)
  ))
_sym_db.RegisterMessage(cvMat)


# @@protoc_insertion_point(module_scope)
